// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2fgN0tGztH4WdD3bFwrdKzOoZIicijmo',
    appId: '1:217033854510:web:b584ca7bcccbb57fc419bf',
    messagingSenderId: '217033854510',
    projectId: 'test-ab-tcc',
    authDomain: 'test-ab-tcc.firebaseapp.com',
    storageBucket: 'test-ab-tcc.appspot.com',
    measurementId: 'G-8899Y28WX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkUpNIJl8BCSp1FDCnAjrOytGBogIRD0',
    appId: '1:217033854510:android:f4b00783bd524404c419bf',
    messagingSenderId: '217033854510',
    projectId: 'test-ab-tcc',
    storageBucket: 'test-ab-tcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQ0TuturKZnkv0MrQKjU3WRZqNmLdBIc',
    appId: '1:217033854510:ios:f81e38854891e0efc419bf',
    messagingSenderId: '217033854510',
    projectId: 'test-ab-tcc',
    storageBucket: 'test-ab-tcc.appspot.com',
    iosClientId: '217033854510-cid11l9ml9ja88na9p2l7c2c5plf97ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccTestAb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlQ0TuturKZnkv0MrQKjU3WRZqNmLdBIc',
    appId: '1:217033854510:ios:f81e38854891e0efc419bf',
    messagingSenderId: '217033854510',
    projectId: 'test-ab-tcc',
    storageBucket: 'test-ab-tcc.appspot.com',
    iosClientId: '217033854510-cid11l9ml9ja88na9p2l7c2c5plf97ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccTestAb',
  );
}
